### ISSUE TITLE
Errors when benchmarking _very_ fast functions

### ISSUE THREAD

**Issue by spencerlyon2** [johnmyleswhite/Benchmark.jl#28]
An example:

```
julia> _f1(x,y) = x > 0.0 && y > 0.0
_f1 (generic function with 1 method)

julia> _f2(x,y) = x*y > 0.0
_f2 (generic function with 1 method)

julia> @benchmark _f1(1.0, 4.134124343)
ERROR: InexactError()
 in trunc at ./float.jl:362
 in execute at /Users/sglyon/.julia/v0.4/Benchmarks/src/execute.jl:130
 in execute at /Users/sglyon/.julia/v0.4/Benchmarks/src/execute.jl:42

julia> @benchmark _f2(1.0, 4.134124343)
ERROR: InexactError()
 in trunc at ./float.jl:362
 in execute at /Users/sglyon/.julia/v0.4/Benchmarks/src/execute.jl:130
 in execute at /Users/sglyon/.julia/v0.4/Benchmarks/src/execute.jl:42
```

**Comment by johnmyleswhite** [comment]
What platform are you on? There's some weirdness in the conversions between integers and floats in the current system.

**Comment by spencerlyon2** [comment]
```
julia> versioninfo()
Julia Version 0.4.0-dev+5693
Commit dcc4596* (2015-06-29 04:36 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.3.0)
  CPU: Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by spencerlyon2** [comment]
If you can give any hints as to where the weirdness happens I'm happy to take a look at it also

**Comment by johnmyleswhite** [comment]
Oh wait, you're working from the old package, not the draft work I've been doing.

**Comment by johnmyleswhite** [comment]
https://github.com/johnmyleswhite/Benchmarks.jl

**Comment by spencerlyon2** [comment]
Ha sorry, I posted the issue to the wrong place.

This is in fact using the new package. (I don't have `Benchmark` without the `s` installed)

**Comment by johnmyleswhite** [comment]
https://github.com/johnmyleswhite/Benchmarks.jl/blob/bfdc485e695fcb367df8fd1cbbf1fdc74ad2a157/src/samples.jl#L22

That vector is technically getting populated with integers, but needs to be floating point data to make the `linreg` function happy. Probably the best thing to do is just keep a record of both the raw integer values and the floating point values.

**Comment by spencerlyon2** [comment]
Ok I can experiment with it. I'll post on the actual repo and link back to this conversation.
